language: bash
services: docker

env:
  - VERSION=7.1-minimum PHP_VERSION=7.1 PHP_EXTRA_PECL_EXTENSIONS=
  - VERSION=7.1 PHP_VERSION=7.1
  - VERSION=7.2-minimum PHP_VERSION=7.2 PHP_EXTRA_PECL_EXTENSIONS=
  - VERSION=7.2 PHP_VERSION=7.2

before_script:
  - env | sort
  - image="fluxaudio/php-fpm:$VERSION"

script:
  - |
    (
      set -Eeuo pipefail
      set -x
      docker build -t "$image" .
    )
after_script:
  - docker images