language: bash
services: docker

env:
  - VERSION=7.1-minimum PHP_VERSION=7.1 PHP_EXTRA_PECL_EXTENSIONS=
  - VERSION=7.1 PHP_VERSION=7.1 PHP_EXTRA_PECL_EXTENSIONS="xdebug apcu"
  - VERSION=7.2-minimum PHP_VERSION=7.2 PHP_EXTRA_PECL_EXTENSIONS=
  - VERSION=7.2 PHP_VERSION=7.2 PHP_EXTRA_PECL_EXTENSIONS="xdebug apcu"

before_script:
  - env | sort
  - image="fluxaudio/php-fpm:$VERSION"

script:
  - docker build -t $image --build-arg PHP_VERSION="$PHP_VERSION" --build-arg PHP_EXTRA_PECL_EXTENSIONS="$PHP_EXTRA_PECL_EXTENSIONS" .
  - docker run --rm $image php -i

after_script:
  - docker images

deploy:
  provider: script
  script: bash bin/docker_push.sh $image
  on:
    branch: master