language: bash
services: docker

env:
  - VERSION=7.1-minimum PHP_VERSION=7.1 PHP_EXTRA_PECL_EXTENSIONS=
  - VERSION=7.1 PHP_VERSION=7.1 PHP_EXTRA_PECL_EXTENSIONS="xdebug apcu"
  - VERSION=7.2-minimum PHP_VERSION=7.2 PHP_EXTRA_PECL_EXTENSIONS=
  - VERSION=7.2 PHP_VERSION=7.2 PHP_EXTRA_PECL_EXTENSIONS="xdebug apcu"

before_script:
  - env | sort
  - image="fluxaudio/php-fpm:$VERSION"

script:
  - |
    (
      set -Eeuo pipefail
      set -x
      docker build -t \
        --build-arg PHP_VERSION="$PHP_VERSION" \
        --build-arg PHP_EXTRA_PECL_EXTENSIONS="$PHP_EXTRA_PECL_EXTENSIONS" \
        .
    )
after_script:
  - docker images